name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: make all
      run: make all
    - name: preparing for use in local directory
      run: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:./build/bin
    - name: unit test
      run: ./build/bin/unit