name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build project
      run: make all

    - name: Run unit tests
      run: |
        cd build/bin
        LD_LIBRARY_PATH=./:$LD_LIBRARY_PATH ./unit
