name: C/C++ CI (Windows,Powershell script)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build project
      run: .\make.ps1 all
    - name: Run unit tests
      run: |
        cd build/bin
        .\unit
